In [1]:
import numpy as np

In [2]:
# Classic array np.array([...], dtype = ...)
array = np.array([1, 2, 3], dtype = float)
print(array)

[1. 2. 3.]


In [3]:
print(array.shape)
print(array.size)

(3,)
3


In [4]:
# Array is mutable(only for compatible data type)
array[0] = 2
print(array)

[2. 2. 3.]


In [5]:
# Arange creates an array by np.arange(start, stop, step)
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


In [6]:
# Linspace creates an array by np.linspace(start, stop, number of values) difference by equal value
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
# Logspace creates an array by np.logspace(start, stop, number of values, base = ...)
logspace = np.logspace(1, 3, 3, base = 2)
print(logspace)

[2. 4. 8.]


In [8]:
# Meshgrid eqalises number of rows and columns to create all possible combinations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [9]:
# Random rand creates array from [0, 1) by np.random.rand(number of values)
random_rand = np.random.rand(5)
print(random_rand)

[0.42956235 0.6141724  0.0945977  0.38143987 0.46942116]


In [10]:
# Random randn creates an array for disribution by np.random.randn(number of values)
random_randn = np.random.randn(5)
print(random_randn)

[ 0.0036813  -0.60460586 -0.56255082 -1.09538417  1.46890673]


In [11]:
# Random randint creates an array by np.random.randint(start, stop, size = ...)
random_randint = np.random.randint(1, 10, size = 5)
print(random_randint)

[9 4 2 9 6]


In [12]:
# Random random creates a matrix from [0, 1) by np.random.random([rows, columns])
random_random = np.random.random([2, 2])
print(random_random)

[[0.09215699 0.97989115]
 [0.39886152 0.37538684]]


In [13]:
# Default generator creates an object to implement methods
rng = np.random.default_rng()
# Random method creates an array from [0, 1) by .random(number of values)
print(rng.random(5))
# Integer method creates an array by .integers(start, stop, size = )
print(rng.integers(1, 10, size = 5))
# Choice chooses by .choice(list, size = ..., replace = True/False )
print(rng.choice([10, 20, 30, 40], size = 3, replace = False))
# Shuffle randomly shuffles an array
arr = np.arange(5)
rng.shuffle(arr)
print(arr)

[0.47191097 0.61694512 0.99378778 0.13660708 0.1525676 ]
[4 8 3 2 6]
[20 40 30]
[3 0 4 1 2]


In [14]:
# Diag either outputs the diagonal of the matrix of gives matrix with 0s and diagonal of given array(k is offset)
print(np.diag([1, 2, 3], k = 0))
arr = np.random.random([3, 3])
print(np.diag(arr))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0.90862943 0.22095685 0.5700607 ]


In [15]:
# Zeros creates zero matrix with np.zeros([rows, columns])
zero_matrix = np.zeros([2, 2])
print(zero_matrix)

[[0. 0.]
 [0. 0.]]


In [16]:
# Ones creates one matrix with np.ones([rows, columns])
ones_matrix = np.ones([2, 2])
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


In [17]:
# Itemsize returns bytes per element
matrix = np.random.random([3, 3])
matrix.itemsize

8

In [18]:
# Nbytes returns total number of bytes
matrix.nbytes

72

In [19]:
# Ndim returns number of dimensions
matrix.ndim

2

In [20]:
# Matrix manipulation
matrix = np.random.randint(1, 10, size = (3, 3))
print(matrix)
print(matrix[1, 1])

[[1 7 5]
 [8 9 1]
 [8 4 9]]
9


In [21]:
# Mask in applying boolean condition to an array
arr = np.random.randint(1, 10, size = 10)
mask = arr > 5
print(arr[mask])
# Also can be applied by np.where()
print(np.where(arr < 5))

[9 7 8 8 8 8 7]
(array([3, 5, 9]),)


In [22]:
# Fancy indexing
arange = np.arange(10)
print(arange)
indexes = [0, 1, 3]
print(arange[indexes])

[0 1 2 3 4 5 6 7 8 9]
[0 1 3]


In [23]:
# Take is similar to fancy indexing but works by np.take(..., [], axis = 0/1)
matrix = np.random.randint(1, 5, size = (3, 3))
print(matrix)
print(np.take(matrix, [0, 2], axis = 0))
print('---------------------')
arr = np.random.randint(1, 5, size = 5)
print(arr)
print(np.take(arr, [0, 3]))
indexes = [0, 3]
# Or
print(arr.take(indexes))
# Or
arr_index = np.take(arr, indexes)
print(arr_index)

[[2 1 1]
 [4 3 3]
 [4 1 1]]
[[2 1 1]
 [4 1 1]]
---------------------
[3 2 2 2 3]
[3 2]
[3 2]
[3 2]


In [24]:
# Matrix multiplication by dot product np.dot(matrix, matrix) !only in same dimension
A = np.random.randint(1, 5, size = (3, 3))
print(A)
print(np.dot(A, A))

[[1 2 3]
 [4 3 2]
 [1 4 1]]
[[12 20 10]
 [18 25 20]
 [18 18 12]]


In [25]:
# .T transforms shape of the matrix (x, y, ...) (..., y, x)
print(A.T)

[[1 4 1]
 [2 3 4]
 [3 2 1]]


In [26]:
import pandas as pd
import numpy as np
arange = np.arange(1, 100)
df = pd.DataFrame(arange)
length = len(df)
index_25 = df.iloc[length // 4]
print(index_25)
index_75 = df.iloc[(length * 3)// 4]
print(index_75)
diff = index_75 - index_25
print(df - diff)

0    25
Name: 24, dtype: int64
0    75
Name: 74, dtype: int64
     0
0  -49
1  -48
2  -47
3  -46
4  -45
..  ..
94  45
95  46
96  47
97  48
98  49

[99 rows x 1 columns]


In [27]:
# Kronecker product
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 5],
              [6, 7]])

# [[1 * 0, 1 * 5, 2 * 0, 2 * 5]
#  [1 * 6, 1 * 7, 2 * 6, 2 * 7]
#  [3 * 0, 3 * 5, 4 * 0, 4 * 5]
#  [3 * 6, 3 * 7, 4 * 6, 4 * 7]]

print(np.kron(A, B))

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [28]:
# Inner product
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# [[1 * 5 + 2 * 6, 1 * 7 + 2 * 6]
#  [3 * 5 + 4 * 6, 3 * 7 + 4 * 8]]
print(np.inner(a, b))

[[17 23]
 [39 53]]


In [30]:
# Cross product between vectors(if matrices, first finds cross product between rows in matrix)
# a = [a1, a2, a3]
# b = [b1, b2, b3]

# a × b =
# [a2*b3 - a3*b2,
#  a3*b1 - a1*b3,
#  a1*b2 - a2*b1]

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.cross(a, b))

[-3  6 -3]


In [35]:
# Multiply multiplies two arrays elementwise np.multiply(array 1, array 2, ....)
a = np.array([[n * m for n in range(5)] for m in range(5)])
b = np.array([[n+m for n in range(5)] for m in range(5)])
c = np.array([[n-m for n in range(5)] for m in range(5)])
print(np.multiply(a, b, c))

[[  0   0   0   0   0]
 [  0   2   6  12  20]
 [  0   6  16  30  48]
 [  0  12  30  54  84]
 [  0  20  48  84 128]]


In [38]:
# Matmul
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# [[1 * 5 + 2 * 7, 1 * 6 + 2 * 8]
#  [3 * 5 + 4 * 7, 3 * 6 + 4 * 8]]
print(np.matmul(a, b))

# @ is the same
print(a @ b)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [48]:
# Conjugate flips the sign in complex numbers
c = np.matrix([1, 2, 3], dtype = complex)
print(c)
print(np.conjugate(c))

[[1.+0.j 2.+0.j 3.+0.j]]
[[1.-0.j 2.-0.j 3.-0.j]]


In [49]:
# .H flips rows and columns(.T) + conjugates
c.H

matrix([[1.-0.j],
        [2.-0.j],
        [3.-0.j]])

In [51]:
# Real and imaginary parts
print(np.real(c))
print(np.imag(c))

[[1. 2. 3.]]
[[0. 0. 0.]]


In [57]:
# Matrix computations
# Eigenvalues, eigenvectors

matrix = np.matrix([[1, 2], [3, 4]])
eig_val, eig_vect = np.linalg.eig(matrix)
print(eig_val)
print(eig_vect)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [58]:
# Mean()
a = np.array([1, 2, 3, 4, 5])
print(np.mean(a))

3.0


In [59]:
# Standard deviation
print(np.std(a))

1.4142135623730951


In [60]:
# Variance
print(np.var(a))

2.0


In [61]:
# Min() and max()
print(np.max(a))
print(np.min(a))

5
1


In [62]:
# Summ and product
print(np.sum(a))
print(np.prod(a))

15
120


In [64]:
# Cumulative sum [1, 2, 3, 4] -> [1, (1+2), (1+2+3), (1+2+3+4)]
print(np.cumsum(a))

[ 1  3  6 10 15]


In [65]:
# Trace is sum of the diagonal (= .diag.sum())
matrix = np.matrix([[1, 2], [3, 4]])
print(np.trace(matrix))

5


In [66]:
# Fliplr to reverse the matrix by columns
print(np.fliplr(matrix))

[[2 1]
 [4 3]]


In [67]:
# Flipud to reverse the matrix by rows
print(np.flipud(matrix))

[[3 4]
 [1 2]]


In [71]:
# Unique to output only unique values(for matrix compares unique rows)
array = np.array([1, 1, 2, 2, 3, 3])
print(np.unique(array))

[1 2 3]


In [73]:
# Axis variables
# axis=0 → squish downward (work column by column)
# axis=1 → squish sideways (work row by row)

In [75]:
# Reshaping
A = np.random.randint(1, 5, size = (3, 2))
print(A)
B = A.reshape(2, 3)
print(B)

[[1 1]
 [4 3]
 [1 1]]
[[1 1 4]
 [3 1 1]]


In [77]:
# Copy to create an independent array
B = A.copy()
print(B)

[[1 1]
 [4 3]
 [1 1]]


In [78]:
# Flatten to turn matrix to a vector
flat = B.flatten()
print(flat)

[1 1 4 3 1 1]


In [79]:
# Repeat
rep = np.repeat(1, 4)
print(rep)

[1 1 1 1]


In [80]:
# Tile
tile = np.tile([[1, 2, 3], [4, 5, 6]], 3)
print(tile)

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [82]:
# Concatenate
# For array
A = np.array([1, 2])
B = np.array([3, 4])
print(np.concatenate([A, B]))
# For matrix
matrix_1 = np.matrix([[1, 2], [3, 4]])
matrix_2 = np.matrix([[5, 6], [7, 8]])
print(np.concatenate([matrix_1, matrix_2], axis = 0))
print(np.concatenate([matrix_1, matrix_2], axis = 1))

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [84]:
# Hstack like concatenate by axis 1
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.hstack((A, B)))

[[1 2 5 6]
 [3 4 7 8]]


In [85]:
# Vstack to concatenate by axis 0
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(np.vstack((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
# Astype to copy the array with another type
type_1 = np.array([1, 2, 3])
type_2 = type_1.astype(float)
print(type_2)

[1. 2. 3.]


In [91]:
# Datetime64 and timedelta64(difference)
d1 = np.datetime64('2025-08-19')
d2 = np.datetime64('2025-08-25')

delta = d2 - d1
print(delta)

6 days
