In [1]:
from zipfile import sizeEndCentDir

import numpy as np

In [8]:
# Classic array np.array([...], dtype = ...)
array = np.array([1, 2, 3], dtype = float)
print(array)

[1. 2. 3.]


In [9]:
print(array.shape)
print(array.size)

(3,)
3


In [10]:
# Array is mutable(only for compatible data type)
array[0] = 2
print(array)

[2. 2. 3.]


In [12]:
# Arange creates an array by np.arange(start, stop, step)
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


In [20]:
# Linspace creates an array by np.linspace(start, stop, number of values) difference by equal value
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [21]:
# Logspace creates an array by np.logspace(start, stop, number of values, base = ...)
logspace = np.logspace(1, 3, 3, base = 2)
print(logspace)

[2. 4. 8.]


In [25]:
# Meshgrid eqalises number of rows and columns to create all possible combinations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [28]:
# Random rand creates array from [0, 1) by np.random.rand(number of values)
random_rand = np.random.rand(5)
print(random_rand)

[0.87607634 0.25781836 0.84186507 0.47776244 0.64483234]


In [29]:
# Random randn creates an array for disribution by np.random.randn(number of values)
random_randn = np.random.randn(5)
print(random_randn)

[-0.59356176  0.65280429 -0.03308658  0.7785043   1.81427514]


In [30]:
# Random randint creates an array by np.random.randint(start, stop, size = ...)
random_randint = np.random.randint(1, 10, size = 5)
print(random_randint)

[3 6 8 2 7]


In [33]:
# Random random creates a matrix from [0, 1) by np.random.random([rows, columns])
random_random = np.random.random([2, 2])
print(random_random)

[[0.45803    0.08543341]
 [0.65266374 0.64595462]]


In [38]:
# Default generator creates an object to implement methods
rng = np.random.default_rng()
# Random method creates an array from [0, 1) by .random(number of values)
print(rng.random(5))
# Integer method creates an array by .integers(start, stop, size = )
print(rng.integers(1, 10, size = 5))
# Choice chooses by .choice(list, size = ..., replace = True/False )
print(rng.choice([10, 20, 30, 40], size = 3, replace = False))
# Shuffle randomly shuffles an array
arr = np.arange(5)
rng.shuffle(arr)
print(arr)

[0.58030572 0.47779656 0.15034088 0.60910842 0.61500008]
[6 7 5 8 5]
[10 40 20]
[1 4 0 2 3]
