In [1]:
import numpy as np

In [2]:
# Classic array np.array([...], dtype = ...)
array = np.array([1, 2, 3], dtype = float)
print(array)

[1. 2. 3.]


In [3]:
print(array.shape)
print(array.size)

(3,)
3


In [4]:
# Array is mutable(only for compatible data type)
array[0] = 2
print(array)

[2. 2. 3.]


In [5]:
# Arange creates an array by np.arange(start, stop, step)
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


In [6]:
# Linspace creates an array by np.linspace(start, stop, number of values) difference by equal value
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
# Logspace creates an array by np.logspace(start, stop, number of values, base = ...)
logspace = np.logspace(1, 3, 3, base = 2)
print(logspace)

[2. 4. 8.]


In [8]:
# Meshgrid eqalises number of rows and columns to create all possible combinations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [9]:
# Random rand creates array from [0, 1) by np.random.rand(number of values)
random_rand = np.random.rand(5)
print(random_rand)

[0.17084781 0.67271337 0.82215986 0.41996771 0.97187642]


In [10]:
# Random randn creates an array for disribution by np.random.randn(number of values)
random_randn = np.random.randn(5)
print(random_randn)

[ 0.71228838 -0.68132391 -1.38676415 -0.58188315 -1.14249123]


In [11]:
# Random randint creates an array by np.random.randint(start, stop, size = ...)
random_randint = np.random.randint(1, 10, size = 5)
print(random_randint)

[6 2 2 5 3]


In [12]:
# Random random creates a matrix from [0, 1) by np.random.random([rows, columns])
random_random = np.random.random([2, 2])
print(random_random)

[[0.99442932 0.77680583]
 [0.66612157 0.20939879]]


In [13]:
# Default generator creates an object to implement methods
rng = np.random.default_rng()
# Random method creates an array from [0, 1) by .random(number of values)
print(rng.random(5))
# Integer method creates an array by .integers(start, stop, size = )
print(rng.integers(1, 10, size = 5))
# Choice chooses by .choice(list, size = ..., replace = True/False )
print(rng.choice([10, 20, 30, 40], size = 3, replace = False))
# Shuffle randomly shuffles an array
arr = np.arange(5)
rng.shuffle(arr)
print(arr)

[0.01058038 0.01386269 0.12243817 0.10699677 0.51463199]
[5 6 5 6 5]
[10 30 40]
[1 4 3 0 2]


In [14]:
# Diag either outputs the diagonal of the matrix of gives matrix with 0s and diagonal of given array(k is offset)
print(np.diag([1, 2, 3], k = 0))
arr = np.random.random([3, 3])
print(np.diag(arr))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0.24473169 0.79975769 0.22983007]


In [15]:
# Zeros creates zero matrix with np.zeros([rows, columns])
zero_matrix = np.zeros([2, 2])
print(zero_matrix)

[[0. 0.]
 [0. 0.]]


In [16]:
# Ones creates one matrix with np.ones([rows, columns])
ones_matrix = np.ones([2, 2])
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


In [17]:
# Itemsize returns bytes per element
matrix = np.random.random([3, 3])
matrix.itemsize

8

In [18]:
# Nbytes returns total number of bytes
matrix.nbytes

72

In [19]:
# Ndim returns number of dimensions
matrix.ndim

2

In [20]:
# Matrix manipulation
matrix = np.random.randint(1, 10, size = (3, 3))
print(matrix)
print(matrix[1, 1])

[[4 5 1]
 [1 8 7]
 [5 7 9]]
8


In [21]:
# Mask in applying boolean condition to an array
arr = np.random.randint(1, 10, size = 10)
mask = arr > 5
print(arr[mask])
# Also can be applied by np.where()
print(np.where(arr < 5))

[6 6 7 8]
(array([0, 3, 7]),)


In [22]:
# Fancy indexing
arange = np.arange(10)
print(arange)
indexes = [0, 1, 3]
print(arange[indexes])

[0 1 2 3 4 5 6 7 8 9]
[0 1 3]


In [23]:
# Take is similar to fancy indexing but works by np.take(..., [], axis = 0/1)
matrix = np.random.randint(1, 5, size = (3, 3))
print(matrix)
print(np.take(matrix, [0, 2], axis = 0))
print('---------------------')
arr = np.random.randint(1, 5, size = 5)
print(arr)
print(np.take(arr, [0, 3]))
indexes = [0, 3]
# Or
print(arr.take(indexes))
# Or
arr_index = np.take(arr, indexes)
print(arr_index)

[[3 4 3]
 [3 2 2]
 [2 4 1]]
[[3 4 3]
 [2 4 1]]
---------------------
[2 3 2 2 2]
[2 2]
[2 2]
[2 2]


In [33]:
# Matrix multiplication by dot product np.dot(matrix, matrix) !only in same dimension
A = np.random.randint(1, 5, size = (3, 3))
print(A)
print(np.dot(A, A))

[[1 4 3]
 [2 2 1]
 [1 1 2]]
[[12 15 13]
 [ 7 13 10]
 [ 5  8  8]]


In [34]:
# .T transforms shape of the matrix (x, y, ...) (..., y, x)
print(A.T)

[[1 2 1]
 [4 2 1]
 [3 1 2]]


In [35]:
import pandas as pd
import numpy as np
arange = np.arange(1, 100)
df = pd.DataFrame(arange)
length = len(df)
index_25 = df.iloc[length // 4]
print(index_25)
index_75 = df.iloc[(length * 3)// 4]
print(index_75)
diff = index_75 - index_25
print(df - diff)

0    25
Name: 24, dtype: int64
0    75
Name: 74, dtype: int64
     0
0  -49
1  -48
2  -47
3  -46
4  -45
..  ..
94  45
95  46
96  47
97  48
98  49

[99 rows x 1 columns]


In [45]:
# Kronecker product
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 5],
              [6, 7]])

# [[1 * 0, 1 * 5, 2 * 0, 2 * 5]
#  [1 * 6, 1 * 7, 2 * 6, 2 * 7]
#  [3 * 0, 3 * 5, 4 * 0, 4 * 5]
#  [3 * 6, 3 * 7, 4 * 6, 4 * 7]]

print(np.kron(A, B))

[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [46]:
# Inner product
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

# [[1 * 5 + 2 * 6, 1 * 7 + 2 * 6]
#  [3 * 5 + 4 * 6, 3 * 7 + 4 * 8]]
print(np.inner(a, b))

[[17 23]
 [39 53]]


In [47]:
# Cross product between vectors(if matrices, first finds cross product between rows in matrix)
# a = [a1, a2, a3]
# b = [b1, b2, b3]

# a × b =
# [a2*b3 - a3*b2,
#  a3*b1 - a1*b3,
#  a1*b2 - a2*b1]

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.cross(a, b))

[-3  6 -3]
