In [53]:
import numpy as np

In [54]:
# Classic array np.array([...], dtype = ...)
array = np.array([1, 2, 3], dtype = float)
print(array)

[1. 2. 3.]


In [55]:
print(array.shape)
print(array.size)

(3,)
3


In [56]:
# Array is mutable(only for compatible data type)
array[0] = 2
print(array)

[2. 2. 3.]


In [57]:
# Arange creates an array by np.arange(start, stop, step)
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


In [58]:
# Linspace creates an array by np.linspace(start, stop, number of values) difference by equal value
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [59]:
# Logspace creates an array by np.logspace(start, stop, number of values, base = ...)
logspace = np.logspace(1, 3, 3, base = 2)
print(logspace)

[2. 4. 8.]


In [60]:
# Meshgrid eqalises number of rows and columns to create all possible combinations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [61]:
# Random rand creates array from [0, 1) by np.random.rand(number of values)
random_rand = np.random.rand(5)
print(random_rand)

[0.16577086 0.98798814 0.58795562 0.29582829 0.53788434]


In [62]:
# Random randn creates an array for disribution by np.random.randn(number of values)
random_randn = np.random.randn(5)
print(random_randn)

[0.3972909  0.06155383 0.923358   0.5599316  1.20971925]


In [63]:
# Random randint creates an array by np.random.randint(start, stop, size = ...)
random_randint = np.random.randint(1, 10, size = 5)
print(random_randint)

[5 7 7 5 7]


In [64]:
# Random random creates a matrix from [0, 1) by np.random.random([rows, columns])
random_random = np.random.random([2, 2])
print(random_random)

[[0.83249903 0.66222297]
 [0.35760808 0.67942404]]


In [65]:
# Default generator creates an object to implement methods
rng = np.random.default_rng()
# Random method creates an array from [0, 1) by .random(number of values)
print(rng.random(5))
# Integer method creates an array by .integers(start, stop, size = )
print(rng.integers(1, 10, size = 5))
# Choice chooses by .choice(list, size = ..., replace = True/False )
print(rng.choice([10, 20, 30, 40], size = 3, replace = False))
# Shuffle randomly shuffles an array
arr = np.arange(5)
rng.shuffle(arr)
print(arr)

[0.03910182 0.97603949 0.98791862 0.4182089  0.44864237]
[2 8 4 7 7]
[40 30 10]
[0 4 2 1 3]


In [66]:
# Diag either outputs the diagonal of the matrix of gives matrix with 0s and diagonal of given array(k is offset)
print(np.diag([1, 2, 3], k = 0))
arr = np.random.random([3, 3])
print(np.diag(arr))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0.61681842 0.69111695 0.65324147]


In [67]:
# Zeros creates zero matrix with np.zeros([rows, columns])
zero_matrix = np.zeros([2, 2])
print(zero_matrix)

[[0. 0.]
 [0. 0.]]


In [68]:
# Ones creates one matrix with np.ones([rows, columns])
ones_matrix = np.ones([2, 2])
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


In [69]:
# Itemsize returns bytes per element
matrix = np.random.random([3, 3])
matrix.itemsize

8

In [70]:
# Nbytes returns total number of bytes
matrix.nbytes

72

In [71]:
# Ndim returns number of dimensions
matrix.ndim

2

In [72]:
# Matrix manipulation
matrix = np.random.randint(1, 10, size = (3, 3))
print(matrix)
print(matrix[1, 1])

[[4 4 3]
 [3 5 8]
 [6 5 4]]
5


In [73]:
# Mask in applying boolean condition to an array
arr = np.random.randint(1, 10, size = 10)
mask = arr > 5
print(arr[mask])
# Also can be applied by np.where()
print(np.where(arr < 5))

[8 8 9 7 8 8]
(array([0, 4]),)


In [74]:
# Fancy indexing
arange = np.arange(10)
print(arange)
indexes = [0, 1, 3]
print(arange[indexes])

[0 1 2 3 4 5 6 7 8 9]
[0 1 3]


In [75]:
# Take is similar to fancy indexing but works by np.take(..., [], axis = 0/1)
matrix = np.random.randint(1, 5, size = (3, 3))
print(matrix)
print(np.take(matrix, [0, 2], axis = 0))
print('---------------------')
arr = np.random.randint(1, 5, size = 5)
print(arr)
print(np.take(arr, [0, 3]))
indexes = [0, 3]
# Or
print(arr.take(indexes))
# Or
arr_index = np.take(arr, indexes)
print(arr_index)

[[2 3 1]
 [2 1 3]
 [2 1 2]]
[[2 3 1]
 [2 1 2]]
---------------------
[4 3 2 2 1]
[4 2]
[4 2]
[4 2]
