In [1]:
import numpy as np

In [2]:
# Classic array np.array([...], dtype = ...)
array = np.array([1, 2, 3], dtype = float)
print(array)

[1. 2. 3.]


In [3]:
print(array.shape)
print(array.size)

(3,)
3


In [4]:
# Array is mutable(only for compatible data type)
array[0] = 2
print(array)

[2. 2. 3.]


In [5]:
# Arange creates an array by np.arange(start, stop, step)
arange = np.arange(0, 10, 2)
print(arange)

[0 2 4 6 8]


In [6]:
# Linspace creates an array by np.linspace(start, stop, number of values) difference by equal value
linspace = np.linspace(1, 10, 5)
print(linspace)

[ 1.    3.25  5.5   7.75 10.  ]


In [7]:
# Logspace creates an array by np.logspace(start, stop, number of values, base = ...)
logspace = np.logspace(1, 3, 3, base = 2)
print(logspace)

[2. 4. 8.]


In [8]:
# Meshgrid eqalises number of rows and columns to create all possible combinations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

X, Y = np.meshgrid(x, y)
print(X)
print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]]


In [9]:
# Random rand creates array from [0, 1) by np.random.rand(number of values)
random_rand = np.random.rand(5)
print(random_rand)

[0.99798578 0.177051   0.13196002 0.38580352 0.45154183]


In [10]:
# Random randn creates an array for disribution by np.random.randn(number of values)
random_randn = np.random.randn(5)
print(random_randn)

[-0.64304935 -2.31942923 -1.00005277 -0.24597606 -0.63212113]


In [11]:
# Random randint creates an array by np.random.randint(start, stop, size = ...)
random_randint = np.random.randint(1, 10, size = 5)
print(random_randint)

[9 2 9 4 4]


In [12]:
# Random random creates a matrix from [0, 1) by np.random.random([rows, columns])
random_random = np.random.random([2, 2])
print(random_random)

[[0.12103682 0.56924336]
 [0.50404711 0.21052217]]


In [13]:
# Default generator creates an object to implement methods
rng = np.random.default_rng()
# Random method creates an array from [0, 1) by .random(number of values)
print(rng.random(5))
# Integer method creates an array by .integers(start, stop, size = )
print(rng.integers(1, 10, size = 5))
# Choice chooses by .choice(list, size = ..., replace = True/False )
print(rng.choice([10, 20, 30, 40], size = 3, replace = False))
# Shuffle randomly shuffles an array
arr = np.arange(5)
rng.shuffle(arr)
print(arr)

[0.0443409  0.04885281 0.50416967 0.44783911 0.62777447]
[6 3 2 6 1]
[20 40 30]
[0 4 2 1 3]


In [14]:
# Diag either outputs the diagonal of the matrix of gives matrix with 0s and diagonal of given array(k is offset)
print(np.diag([1, 2, 3], k = 0))
arr = np.random.random([3, 3])
print(np.diag(arr))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[0.32860954 0.06139764 0.21292647]


In [15]:
# Zeros creates zero matrix with np.zeros([rows, columns])
zero_matrix = np.zeros([2, 2])
print(zero_matrix)

[[0. 0.]
 [0. 0.]]


In [16]:
# Ones creates one matrix with np.ones([rows, columns])
ones_matrix = np.ones([2, 2])
print(ones_matrix)

[[1. 1.]
 [1. 1.]]


In [17]:
# Itemsize returns bytes per element
matrix = np.random.random([3, 3])
matrix.itemsize

8

In [18]:
# Nbytes returns total number of bytes
matrix.nbytes

72

In [19]:
# Ndim returns number of dimensions
matrix.ndim

2

In [20]:
# Matrix manipulation
matrix = np.random.randint(1, 10, size = (3, 3))
print(matrix)
print(matrix[1, 1])

[[1 5 2]
 [6 3 1]
 [9 2 7]]
3


In [21]:
# Mask in applying boolean condition to an array
arr = np.random.randint(1, 10, size = 10)
mask = arr > 5
print(arr[mask])
# Also can be applied by np.where()
print(np.where(arr < 5))

[6 9 8 7 6 8]
(array([1, 5, 8, 9]),)


In [22]:
# Fancy indexing
arange = np.arange(10)
print(arange)
indexes = [0, 1, 3]
print(arange[indexes])

[0 1 2 3 4 5 6 7 8 9]
[0 1 3]


In [23]:
# Take is similar to fancy indexing but works by np.take(..., [], axis = 0/1)
matrix = np.random.randint(1, 5, size = (3, 3))
print(matrix)
print(np.take(matrix, [0, 2], axis = 0))
print('---------------------')
arr = np.random.randint(1, 5, size = 5)
print(arr)
print(np.take(arr, [0, 3]))
indexes = [0, 3]
# Or
print(arr.take(indexes))
# Or
arr_index = np.take(arr, indexes)
print(arr_index)

[[3 2 4]
 [2 2 1]
 [1 4 2]]
[[3 2 4]
 [1 4 2]]
---------------------
[1 4 4 2 3]
[1 2]
[1 2]
[1 2]


In [24]:
import pandas as pd
import numpy as np

x = np.arange(1, 100)
y = 2 ** x
df = pd.DataFrame({'x': x, 'y': y})
df_new = df.sample(frac=2/3).sort_index()
mean = df['x'].mean()
std = df['x'].std()
print(mean, std)
df_filtered = df[(df['x'] > mean + 2*std) | (df['x'] < mean - 2*std)]
print(df_filtered)

50.0 28.722813232690143
Empty DataFrame
Columns: [x, y]
Index: []


In [25]:
# Matrix multiplication by dot product np.dot(matrix, matrix)
A = np.random.randint(1, 5, size = (3, 3))
print(A)
print(np.dot(A, A))

[[2 3 3]
 [1 2 2]
 [1 2 2]]
[[10 18 18]
 [ 6 11 11]
 [ 6 11 11]]


In [26]:
# .T transforms shape of the matrix (x, y, ...) (..., y, x)
print(A.T)

[[2 1 1]
 [3 2 2]
 [3 2 2]]
