In [1]:
# 1. 1-dən 101-ə qədər 5x5 ölçülü təsadüfi tam ədədlərdən ibarət matris yaradın.
# Daha sonra bu matrisdən yalnız cüt indekslərdə yerləşən (həm sətir, həm sütun indeksi cüt olan) elementləri çıxarın
# və yeni bir matris yaradın.

import numpy as np

# 1. 5x5 ölçülü təsadüfi tam ədədlər (1-101)
matris = np.random.randint(1, 102, size=(5, 5))
print("Əsas matris:")
print(matris)

# 2. Cüt indekslərdəki elementləri seçmək (0, 2, 4...)
yeni_matris = matris[::2, ::2]  # sətir və sütunlarda addım 2
print("\nCüt indekslərdəki elementlərdən ibarət yeni matris:")
print(yeni_matris)

Əsas matris:
[[32 27 54 43 11]
 [62 95 76 73 94]
 [14 89 75 60 77]
 [ 5 79 83 95 93]
 [68 30 55 50 53]]

Cüt indekslərdəki elementlərdən ibarət yeni matris:
[[32 54 11]
 [14 75 77]
 [68 55 53]]


In [2]:
# 2. 1-dən 20-yə qədər ardıcıl ədədlərdən ibarət massiv yaradın.
# Daha sonra bu massivdə yalnız 3-ə və 5-ə bölünən ədədləri tapın.
import numpy as np

# 1-dən 20-yə qədər ardıcıl ədədlərdən ibarət massiv
arr = np.arange(1, 21)

# 3-ə və 5-ə bölünən ədədlər
result = arr[(arr % 3 == 0) & (arr % 5 == 0)]

print(result)


[15]


In [3]:
# 3. 4x4 ölçülü təsadüfi onluq ədədlərdən ibarət matris yaradın. Hər bir sütunun maksimum dəyərini tapın.
import numpy as np

# 4x4 ölçülü təsadüfi onluq ədədlərdən ibarət matris yaradılır
matrix = np.random.rand(4, 4)

# Hər bir sütunun maksimum dəyərini tapırıq
max_per_column = matrix.max(axis=0)

print("Matris:")
print(matrix)
print("\nHər sütunun maksimum dəyəri:")
print(max_per_column)


Matris:
[[0.90852968 0.38261047 0.63307756 0.01156474]
 [0.79331443 0.69088449 0.11436296 0.46508101]
 [0.53901035 0.16229763 0.88074831 0.35390839]
 [0.17413518 0.85727899 0.06437269 0.90178046]]

Hər sütunun maksimum dəyəri:
[0.90852968 0.85727899 0.88074831 0.90178046]


In [4]:
# 4. 1-dən 100-ə qədər təsadüfi tam ədədlərdən ibarət 10 elementlik massiv yaradın.
# Daha sonra massivdəki bütün elementləri kiçikdən böyüyə doğru sıralayın.
import numpy as np

# 1-dən 100-ə qədər təsadüfi tam ədədlərdən ibarət 10 elementlik massiv yaradılır
arr = np.random.randint(1, 101, size=10)

print("Təsadüfi massiv:")
print(arr)

# Massivi kiçikdən böyüyə sıralayırıq
sorted_arr = np.sort(arr)

print("\nSıralanmış massiv:")
print(sorted_arr)


Təsadüfi massiv:
[ 84  31  98  89  47  72 100  59  57  85]

Sıralanmış massiv:
[ 31  47  57  59  72  84  85  89  98 100]


In [6]:
# 5. 1-dən 101-ə qədər 6x6 ölçülü təsadüfi tam ədədlərdən ibarət matris yaradın.
# Matrisin əsas diaqonalında yerləşən elementləri çıxarın və cəmini hesablayın.

In [23]:
matrix = np.random.randint(1, 101, size = (6, 6))
diag = np.diag(matrix)
diag_sum = sum(diag)
print(f'Diagonal sum = {diag_sum}')

Diagonal sum = 338


In [24]:
# 6. 1-dən 25-ə qədər olan ədədləri bir massivdə saxlayın. Bu massivdən 5x5 ölçülü bir matris yaradın və
# həmin matrisin hər bir sütununun kvadratlarını hesablayaraq yeni matris yaradın. (Sadəcə np funksiyaları istifadə edin)

In [25]:
arr = np.arange(1, 26)
matrix = arr.reshape(5, 5)
matrix_squared = np.square(matrix)
print(matrix_squared)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


In [26]:
# 7. 2-dən 10-a qədər sadəcə cüt ədədlərdən ibarət bir massiv yaradın və
# həmin massivdən əsas diaqonalı həmin ədədlərdən ibarət olan bir matris yaradın.

In [29]:
arr = np.arange(2, 11, 2)
diag_matrix = np.diag(arr)
print(diag_matrix)

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


In [17]:
# 8. Tələbələrin adı, fənn adı və imtahan nəticələrini saxlayan DataFrame yaradın.
# Yalnız 80 və ya daha çox bal toplayan tələbələri seçərək yeni DataFrame yaradın

In [2]:
import pandas as pd
data = {'Name': ['Mark', 'Tony', 'Michael'], 'Subject': ['Math', 'History', 'Chemistry'], 'Score': [75, 90, 95]}
df = pd.DataFrame(data)
A = df[df['Score'] > 80]
print(A)

      Name    Subject  Score
1     Tony    History     90
2  Michael  Chemistry     95


In [3]:
# 9. Fərqli mağazaların (şəhərlər üzrə), məhsulların və satış rəqəmlərini saxlayan DataFrame yaradın.
# Hər bir mağaza üzrə məhsul satışlarının toplamını hesablayın.

In [4]:
data = {'City': ['Baku', 'Baku', 'London', 'London', 'Madrid', 'Madrid'], 'Product': ['Milk', 'Egg', 'Milk', 'Egg', 'Milk', 'Egg'], 'Sales': [2, 1, 4, 5, 10, 15]}
df = pd.DataFrame(data)
df_sum = df.groupby('City')['Sales'].sum()
print(df_sum)

City
Baku       3
London     9
Madrid    25
Name: Sales, dtype: int64


In [5]:
# 10. Bir il ərzində aylıq temperatur məlumatlarını saxlayan DataFrame yaradın. Hər mövsüm üçün orta temperaturu hesablayın

In [6]:
data = {"Month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],"Temperature": [4, 6, 10, 15, 20, 25, 28, 27, 22, 16, 10, 6]}
df = pd.DataFrame(data)
season_map = {"Jan": "Winter", "Feb": "Winter", "Dec": "Winter", "Mar": "Spring", "Apr": "Spring", "May": "Spring","Jun": "Summer", "Jul": "Summer", "Aug": "Summer","Sep": "Autumn", "Oct": "Autumn", "Nov": "Autumn"}
df["Season"] = df["Month"].map(season_map)
avg_temp_per_season = df.groupby("Season")["Temperature"].mean()
print(avg_temp_per_season)

Season
Autumn    16.000000
Spring    15.000000
Summer    26.666667
Winter     5.333333
Name: Temperature, dtype: float64


In [15]:
import numpy as np
k = int(input('Enter number of columns: '))
n = int(input('Enter number of rows: '))
a = list(range(1, k + 1))
print(f'Values of k: {a}')
print('------------')
y = []
for x in a:
    i = n - (2 ** (n - x))
    y.append(i)
print(y)
print('------------')
matrix = np.random.rand(n, k)
print(matrix)
print('------------')
result = [matrix[y[i], i] for i in range(k)]
print(result)

Enter number of columns:  4
Enter number of rows:  4


Values of k: [1, 2, 3, 4]
------------
[-4, 0, 2, 3]
------------
[[0.24752927 0.39323971 0.62483812 0.14842657]
 [0.14903338 0.83155993 0.64429523 0.96989772]
 [0.3681476  0.82406528 0.43673624 0.80941803]
 [0.33773289 0.00331511 0.18016737 0.31086501]]
------------
[0.24752927315801954, 0.39323970893239524, 0.43673623974508213, 0.3108650105633066]


In [27]:
import pandas as pd
import numpy as np
dates = pd.date_range(start="2024-01-01", periods=20, freq="D")
df = pd.DataFrame({
    "Date": dates,
    "Temperature": np.random.randint(-5, 35, size=20), 
    "Humidity": np.random.randint(20, 100, size=20),    
    "WindSpeed": np.random.uniform(0, 15, size=20),     
    "Rainfall": np.random.uniform(0, 20, size=20)       
})
df.set_index("Date", inplace=True)
random_date = np.random.choice(df.index)
start_index = df.index.get_loc(random_date)
df["Desc"] = None
df.iloc[start_index:, df.columns.get_loc("Desc")] = np.arange(len(df) - start_index, 0, -1)
print(df)

            Temperature  Humidity  WindSpeed   Rainfall  Desc
Date                                                         
2024-01-01            4        23  11.565596  15.957687  None
2024-01-02           15        99   3.902483  16.999616    19
2024-01-03            0        78   5.843653  14.405335    18
2024-01-04           11        92  14.223190  10.109395    17
2024-01-05           14        27   1.023066  17.640390    16
2024-01-06           16        39  12.213004  11.851194    15
2024-01-07           14        29  10.633711  13.549151    14
2024-01-08           29        33  13.698633  19.774122    13
2024-01-09           18        80  11.844883  16.415439    12
2024-01-10           13        33   8.873558   3.945878    11
2024-01-11           11        56  11.367056  18.670360    10
2024-01-12            3        84   3.284138  13.956091     9
2024-01-13           33        51   4.222458  18.642136     8
2024-01-14           28        44   0.639081  13.124810     7
2024-01-